
services:
  backend:
    container_name: unicarioca_backend
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    container_name: unicarioca_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

  mongo:
    container_name: unicarioca_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
